# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(457, 533)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_generate = QtWidgets.QPushButton(self.centralwidget)
        self.btn_generate.setGeometry(QtCore.QRect(140, 450, 161, 24))
        self.btn_generate.setStyleSheet("borter: 2px;\n"
"border-radius: 10px;\n"
"background-color: #FF0000;\n"
"color: white;")
        self.btn_generate.setObjectName("btn_generate")
        self.cb_numbers = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_numbers.setGeometry(QtCore.QRect(50, 310, 171, 20))
        self.cb_numbers.setStyleSheet("color: white;\n"
"background-color: red;\n"
"border: 2px;\n"
"border-radius: 10px;")
        self.cb_numbers.setObjectName("cb_numbers")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(50, 270, 181, 20))
        self.checkBox.setStyleSheet("color: white;\n"
"background-color: red;\n"
"border: 2px;\n"
"border-radius: 10px;")
        self.checkBox.setObjectName("checkBox")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(110, 60, 224, 28))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setStyleSheet("color: white;\n"
"background-color: red;\n"
"border: 2px;\n"
"border-radius: 10px;")
        self.title.setObjectName("title")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(50, 230, 121, 16))
        self.result.setStyleSheet("color: white;\n"
"background-color: red;\n"
"border: 2px;\n"
"border-radius: 10px;")
        self.result.setObjectName("result")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_generate.setText(_translate("MainWindow", "Згенерувати"))
        self.cb_numbers.setText(_translate("MainWindow", "Використовувати числа"))
        self.checkBox.setText(_translate("MainWindow", "Використовувати алфавіт"))
        self.title.setText(_translate("MainWindow", "Генератор паролів"))
        self.result.setText(_translate("MainWindow", "Тут буде результат"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
